# Generated by Django 3.0.8 on 2020-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='taginpost',
            field=models.ManyToManyField(blank=True, related_name='taged_post', to='posts.Tag'),
        ),
    ]
