# Generated by Django 3.0.8 on 2020-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200715_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15)),
                ('comment', models.ManyToManyField(to='posts.Comment')),
                ('post', models.ManyToManyField(to='posts.Post')),
            ],
        ),
    ]
