# Generated by Django 3.0.8 on 2020-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='tag',
            name='comment',
            field=models.ManyToManyField(related_name='taged_comments', to='posts.Comment'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='taged_posts', to='posts.Post'),
        ),
    ]
