# Generated by Django 3.0.8 on 2020-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200715_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='comment',
            field=models.ManyToManyField(related_name='taged_comments', to='posts.Comment'),
        ),
    ]
