# Generated by Django 3.0.8 on 2020-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200715_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='taged_comments', to='posts.Comment'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(null=True, related_name='taged_posts', to='posts.Post'),
        ),
    ]
