# Generated by Django 3.0.8 on 2020-07-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200715_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='comment',
            new_name='tagincomment',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='post',
            new_name='taginpost',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagincomment',
            field=models.ManyToManyField(null=True, related_name='taged_comments', to='posts.Comment'),
        ),
    ]
