# Generated by Django 3.0.8 on 2020-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200716_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagincomment',
            field=models.ManyToManyField(related_name='taged_comment', to='posts.Comment'),
        ),
        migrations.AddField(
            model_name='tag',
            name='taginpost',
            field=models.ManyToManyField(related_name='taged_post', to='posts.Post'),
        ),
        migrations.DeleteModel(
            name='Tag_post',
        ),
    ]
