# Generated by Django 3.0.8 on 2020-07-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200716_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tagincomment',
            field=models.ManyToManyField(related_name='taged_comment', to='posts.Tag'),
        ),
    ]
