# Generated by Django 3.0.8 on 2020-07-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_comment_tagincomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='taginpost',
            field=models.ManyToManyField(null=True, related_name='taged_post', to='posts.Tag'),
        ),
    ]
