# Generated by Django 3.0.8 on 2020-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20200716_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='taginpost',
            field=models.ManyToManyField(related_name='taged_post', to='posts.Tag'),
        ),
    ]
