# Generated by Django 3.0.8 on 2020-07-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='followers',
            new_name='follows',
        ),
    ]
