# Generated by Django 3.0.8 on 2020-07-27 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200727_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='follows',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
